Add a windows os and a testing to the CI
Alexander-Ploskin/SLIV pull request #161
Opened 2023-04-07 21:29 UTC by mi-sts

2023-04-08 17:59 UTC, Alexander-Ploskin requested changes

2023-04-08 17:59 UTC, Alexander-Ploskin commented on .github/workflows/build.yml
> +        os: [ubuntu-latest, windows-latest]
Test also on macOS

2023-04-09 10:32 UTC, Alexander-Ploskin approved these changes

2023-04-10 04:34 UTC, DmiitriyJarosh approved these changes

2023-04-10 04:34 UTC, merged