Add tests for a planes parser
Alexander-Ploskin/SLIV pull request #176
Opened 2023-04-12 15:36 UTC by mi-sts

Close #154

2023-04-13 17:47 UTC, DmiitriyJarosh requested changes

2023-04-13 17:47 UTC, DmiitriyJarosh commented on src/test/kotlin/solve/parsers/planes/ImagePlanesParserTest.kt
> +    @Test
what about tests for incorrect format? (not image for example) What about tests with overlapped planes? when one plane is inside another

2023-04-13 18:04 UTC, mi-sts commented on src/test/kotlin/solve/parsers/planes/ImagePlanesParserTest.kt
> +    @Test
Now the image parser just take different pixels and their colors, so how we can determine if there are overlapped planes? As far as I remember, at the time of implementation we needed only such functionality

2023-04-14 16:47 UTC, Alexander-Ploskin approved these changes

2023-04-14 16:47 UTC, Alexander-Ploskin commented on src/test/kotlin/solve/parsers/ImageParserTestUtils.kt
> +
space

2023-04-16 16:26 UTC, Alexander-Ploskin approved these changes

2023-04-16 18:45 UTC, DmiitriyJarosh approved these changes

2023-04-16 18:45 UTC, merged