Side panels materialfx
Alexander-Ploskin/SLIV pull request #178
Opened 2023-04-21 20:57 UTC by Anastasia-Nikitina

2023-04-23 18:17 UTC, Alexander-Ploskin requested changes

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/main/MainView.kt
> +        style = "-fx-font-family: ${Style.font}; -fx-font-weight:700;  -fx-font-size: ${Style.buttonFontSize}; -fx-text-fill: ${Style.primaryColorLight}; -fx-background-radius: 36"
This code seems to be common for all side panel buttons (help, settings, etc.)

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/main/MainView.kt
> +
space

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/main/MainView.kt
> +        content.padding = Insets(0.0,0.0,10.0,0.0)
The same as for other PR

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/styles/MFXButtonStyleSheet.kt
> +
spaces

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/constants/ResourcesPaths.kt
> -const val IconsSidePanelVisualizationSettingsPath = "icons/sidepanel/visualization_settings.png"
Did you remove these icons?

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/importer/view/ControlPanel.kt
> +        MaterialFXDialog.changeContent(find<MainView>().content, LoadingScreen().root)
Move MainView into the field and get it by inject()

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/importer/view/ControlPanel.kt
> +        MaterialFXDialog.changeContent(find<MainView>().content, LoadingScreen().root)
The same for LoadingScreen

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/importer/view/ControlPanel.kt
> +            find<MainView>().dialog.close()
Move MainView into the field and get it by inject()

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/importer/view/LoadingScreen.kt
> +                                find<ControlPanel>().coroutineScope.cancel()
Move ControlPanel into the field and get it by inject()

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/main/MainView.kt
> +    val importer = find<ImporterView>()
by inject

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/main/MainView.kt
> +    private val importFAB = mfxButton {
naming

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/main/MainView.kt
> +        val circle = Circle(this.layoutX + 28.0, this.layoutY + 28.0,28.0)
space, move radius into a const

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/main/MainView.kt
> +        VBox.setMargin(this, Insets(5.0, 8.0,10.0,8.0))
spaces

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/main/MainView.kt
> +    private val pluginsButton = mfxButton("Plugins") {
Don't show unused tabs (plugins, settings, help) before the better times (don't remove the code and icons)

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/main/MainView.kt
> +        prefWidth = 70.0
Why you set size only for this button? It actually affects background circle
![image](https://user-images.githubusercontent.com/55746901/233857438-86c298d0-649a-454d-9e04-61775c077854.png)
![image](https://user-images.githubusercontent.com/55746901/233857448-24f81885-8810-4521-8a5c-610cb3d74686.png)

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/styles/MFXButtonStyleSheet.kt
> +       }
codestyle

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/main/MainView.kt
> +        padding = Insets(0.0, 0.0,0.0,0.0)
can use paddingAll

2023-04-23 18:17 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/styles/Style.kt
> +        fun circleForRipple(button: MFXButton) = Circle(button.layoutX + 36.0, button.layoutY + 36.0,35.0)
space

2023-04-23 18:55 UTC, Alexander-Ploskin requested changes

2023-04-23 18:55 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/main/MainView.kt
> +        VBox.setMargin(this, Insets(12.0, 6.0, 0.0, 6.0))
Wrong top margin

Desired:
![image](https://user-images.githubusercontent.com/55746901/233859271-e8b8107e-0f30-44e6-9ca3-4cec4f3917f4.png)

Actual:
![image](https://user-images.githubusercontent.com/55746901/233859256-05caa33b-fc7c-4386-9a7f-055ee2ad2d00.png)

2023-04-27 09:06 UTC, Anastasia-Nikitina commented on src/main/kotlin/solve/main/MainView.kt
> +        style = "-fx-font-family: ${Style.font}; -fx-font-weight:700;  -fx-font-size: ${Style.buttonFontSize}; -fx-text-fill: ${Style.primaryColorLight}; -fx-background-radius: 36"
this is fixed

2023-04-27 09:09 UTC, Anastasia-Nikitina commented on src/main/kotlin/solve/main/MainView.kt
> +        content.padding = Insets(0.0,0.0,10.0,0.0)
this is fixed

2023-04-27 09:11 UTC, Anastasia-Nikitina commented on src/main/kotlin/solve/constants/ResourcesPaths.kt
> -const val IconsSidePanelVisualizationSettingsPath = "icons/sidepanel/visualization_settings.png"
this is fixed

2023-04-27 12:11 UTC, Alexander-Ploskin requested changes

2023-04-27 12:11 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/main/MainView.kt
> +        content = MaterialFXDialog.createGenericDialog(ImporterView().root)
by inject()

2023-04-28 19:05 UTC, Alexander-Ploskin approved these changes

2023-04-28 19:05 UTC, Alexander-Ploskin commented on src/main/kotlin/solve/importer/ProjectParser.kt
> +
space

2023-05-04 20:26 UTC, DmiitriyJarosh approved these changes

2023-05-08 23:39 UTC, merged