Adding guides for working with the application
Alexander-Ploskin/SLIV pull request #193
Opened 2023-05-09 14:53 UTC by Anastasia-Nikitina

2023-05-09 15:02 UTC, Alexander-Ploskin requested changes

2023-05-09 15:02 UTC, Alexander-Ploskin commented on README.md
> +1. Create the Images folder, in which we put all the frames from the dataset. They should be numbered in order and be in jpg or png format.
1. What means ` They should be numbered in order`? What about timestamps?
2. Say about images format.

2023-05-09 15:02 UTC, Alexander-Ploskin commented on README.md
> +2.  Create folders based on the number of algorithms present in the project. You need to name them in the format name-algorithm_landmark (example: alg1_line)
1. Space
2. First sentence -> `For each used landmark detection algorithm create a separate folder.`
3.  `_` instead of `-`, say about planes and keypoints explicitly.

2023-05-09 15:02 UTC, Alexander-Ploskin commented on README.md
> +3. Put files with markup in each of the folders. They should be numbered according to the frames in the project
What about timestamps?

2023-05-09 15:02 UTC, Alexander-Ploskin commented on README.md
> +    1. Points are represented in csv file format, where the first line is used as a header (uid,x,y), and subsequent lines contain data directly (uid, x and y coordinates separated by commas)
Don't say about .csv format itstelf, only about columns.

2023-05-09 15:02 UTC, Alexander-Ploskin commented on README.md
> +    2. Lines are represented in csv file format, where the first line is used as a header (uid,x0,y0,x1,y1), and subsequent lines contain data directly (uid, coordinates of the beginning and coordina
Don't say about .csv format itstelf, only about columns.

2023-05-09 15:02 UTC, Alexander-Ploskin commented on README.md
> +    3. The planes are represented as a png file.
More details about colors and empty space.

2023-05-09 15:02 UTC, Alexander-Ploskin commented on README.md
> +## How do I create a project of the correct format?
Add hyperlinks to examples of planes, lines and keypoints projects in the repo.

2023-05-09 15:17 UTC, DmiitriyJarosh commented on README.md
> +2.  Create folders based on the number of algorithms present in the project. You need to name them in the format name-algorithm_landmark (example: alg1_line)
use code insert or some other text format to highlight name of folder

2023-05-09 15:18 UTC, DmiitriyJarosh commented on README.md
> +    1. Points are represented in csv file format, where the first line is used as a header (uid,x,y), and subsequent lines contain data directly (uid, x and y coordinates separated by commas)
add example link

2023-05-09 15:18 UTC, DmiitriyJarosh commented on README.md
> +3. Put files with markup in each of the folders. They should be numbered according to the frames in the project
add example link

2023-05-09 15:18 UTC, DmiitriyJarosh commented on README.md
> +    2. Lines are represented in csv file format, where the first line is used as a header (uid,x0,y0,x1,y1), and subsequent lines contain data directly (uid, coordinates of the beginning and coordina
add example link

2023-05-09 15:18 UTC, DmiitriyJarosh commented on README.md
> +    3. The planes are represented as a png file.
add example link

2023-05-09 16:35 UTC, Alexander-Ploskin requested changes

2023-05-09 16:35 UTC, Alexander-Ploskin commented on README.md
> +    * 640x480 format
concrete size is not required, images can be of any size, say that all images should have the same size.

2023-05-09 16:35 UTC, Alexander-Ploskin commented on README.md
> +    1. Points are represented file, where the first line is used as a header (uid,x,y), and subsequent lines contain
just say use .csv with (uid,x,y) columns, don't say about csv format lines.

2023-05-09 18:44 UTC, DmiitriyJarosh requested changes

2023-05-09 18:44 UTC, DmiitriyJarosh commented on README.md
> +    * file name is timestamp
what about timstamp format?

2023-05-09 18:44 UTC, DmiitriyJarosh commented on README.md
> +1. Create the ```Images``` folder, in which we put all the frames from the dataset. Images must match the following
we put --- `we`?

2023-05-09 18:44 UTC, DmiitriyJarosh commented on README.md
> +2. For each used landmark detection algorithm create a separate folder. You need to name them in the
them?? **it**

2023-05-09 18:44 UTC, DmiitriyJarosh commented on README.md
> +    1. Points are represented in .csv file with (uid,x,y) columns. <code>[Example](https://github.com/prime-slam/SOLVE/tree/master/testData/TestProject2/alg1_keypoint)</code>
where x, y is??

2023-05-09 18:44 UTC, DmiitriyJarosh commented on README.md
> +    2. Lines are represented in .csv file with (uid,x0,y0,x1,y1) columns. <code>[Example](https://github.com/prime-slam/SOLVE/tree/master/testData/LinesAndKeyPointsProject/alg1_line)</code>
where x, y is??

2023-05-10 19:41 UTC, DmiitriyJarosh requested changes

2023-05-10 19:41 UTC, DmiitriyJarosh commented on README.md
> +    2. Lines are represented in .csv file with (uid,x0,y0,x1,y1) columns, where x0,y0,x1,y1 is coordinates of the
**is** coordinates --- are

2023-05-10 19:41 UTC, DmiitriyJarosh commented on README.md
> +    2. Lines are represented in .csv file with (uid,x0,y0,x1,y1) columns, where x0,y0,x1,y1 is coordinates of the
also uid is skipped in description everywhere

2023-05-10 20:25 UTC, merged