Importer
Alexander-Ploskin/SLIV pull request #23
Opened 2022-10-19 14:40 UTC by Anastasia-Nikitina

2022-10-19 16:42 UTC, Alexander-Ploskin commented on src/main/kotlin/sliv/tool/menubar/view/MenuBarView.kt
> +                ImporterView().openWindow()
Modal window is more suitable here

2022-10-19 17:47 UTC, DmiitriyJarosh requested changes

2022-10-19 17:47 UTC, DmiitriyJarosh commented on src/main/kotlin/sliv/tool/importer/view/ChoosingDirectoryView.kt
> +
why so much space?

2022-10-19 17:47 UTC, DmiitriyJarosh commented on src/main/kotlin/sliv/tool/importer/view/ChoosingDirectoryView.kt
> +        button("Change"){
spaces `){`

2022-10-19 17:47 UTC, DmiitriyJarosh commented on src/main/kotlin/sliv/tool/importer/view/ChoosingDirectoryView.kt
> +        button("Change"){
and everywhere

2022-10-19 17:47 UTC, DmiitriyJarosh commented on src/main/kotlin/sliv/tool/importer/view/ChoosingDirectoryView.kt
> +                directoryChooser.title = ("Choose working directory")
can we do this once when it is created?

2022-10-19 17:47 UTC, DmiitriyJarosh commented on src/main/kotlin/sliv/tool/scene/controller/SceneController.kt
> +
why is it added?

2022-10-21 11:09 UTC, Anastasia-Nikitina commented on src/main/kotlin/sliv/tool/importer/view/ChoosingDirectoryView.kt
> +                directoryChooser.title = ("Choose working directory")
It seems we can't

2022-10-21 11:10 UTC, Anastasia-Nikitina commented on src/main/kotlin/sliv/tool/scene/controller/SceneController.kt
> +
it was an accident. I'll fix it

2022-10-21 20:44 UTC, Alexander-Ploskin commented on src/main/kotlin/sliv/tool/importer/model/LandmarkType.kt
> +enum class LandmarkType { KeyPoint, Line, Plane }
This class already exists in the master branch, rebase to avoid duplications

2022-10-21 20:46 UTC, Alexander-Ploskin commented on src/main/kotlin/sliv/tool/importer/model/ProjectFile.kt
> +open class ProjectFile(val name: String, val directoryPath: Path) {
sealed class should be used here

2022-10-22 07:22 UTC, DmiitriyJarosh commented on src/main/kotlin/sliv/tool/importer/view/ChoosingDirectoryView.kt
> +                directoryChooser.title = ("Choose working directory")
why?

2022-10-27 19:07 UTC, DmiitriyJarosh requested changes

2022-10-27 19:07 UTC, DmiitriyJarosh commented on src/main/kotlin/sliv/tool/importer/model/ProjectFile.kt
> +sealed class ProjectFile(val name: String, val directoryPath: Path) {
delete now as not used

2022-10-27 19:07 UTC, DmiitriyJarosh commented on src/main/kotlin/sliv/tool/importer/model/Output.kt
> +class Output(name: String, directoryPath: Path, val type: LayerKind) : ProjectFile(name, directoryPath) {
delete now as not used

2022-10-27 19:07 UTC, DmiitriyJarosh commented on src/main/kotlin/sliv/tool/importer/model/Image.kt
> +class Image(name: String, directoryPath: Path, var outputs: List<Output>) : ProjectFile(name, directoryPath) {
delete now as not used

2022-10-27 19:07 UTC, DmiitriyJarosh commented on src/main/kotlin/sliv/tool/importer/view/FileView.kt
> +class FileView(val name: String, val icon: javafx.scene.image.Image) {
delete now as not used

2022-10-27 19:07 UTC, DmiitriyJarosh commented on src/main/kotlin/sliv/tool/menubar/view/MenuBarView.kt
> +            action{
skipped space `action {`

2022-10-27 19:07 UTC, DmiitriyJarosh commented on src/main/kotlin/sliv/tool/importer/view/FileStructureView.kt
> +class FileStructureView : Fragment() {
delete now as not used

2022-11-04 08:56 UTC, DmiitriyJarosh approved these changes

2022-11-14 18:37 UTC, merged