Fix break when columns count was not a divisor of the frames count
Alexander-Ploskin/SLIV pull request #70
Opened 2022-11-29 08:36 UTC by Alexander-Ploskin

UI: [imgur](https://imgur.com/a/sx1mLa3)

2022-11-30 19:05 UTC, DmiitriyJarosh requested changes

2022-11-30 19:05 UTC, DmiitriyJarosh commented on src/main/kotlin/sliv/tool/scene/view/FrameView.kt
> +            clearImage()
you have already cleared image before

2022-11-30 19:05 UTC, DmiitriyJarosh commented on src/main/kotlin/sliv/tool/scene/view/SceneView.kt
> +        val emptyFrames = (0 until (30 - scene.frames.count() % columnsNumber)).map { null }
`30` hardcoded

2022-12-01 21:33 UTC, DmiitriyJarosh approved these changes

2022-12-01 21:33 UTC, DmiitriyJarosh commented on src/main/kotlin/sliv/tool/scene/view/SceneView.kt
> +        val emptyFrames = (0 until (columnsNumber - scene.frames.count() % columnsNumber)).map { null }
can we use `repeat` here?

2022-12-01 21:33 UTC, merged

2022-12-02 09:03 UTC, Alexander-Ploskin commented on src/main/kotlin/sliv/tool/scene/view/SceneView.kt
> +        val emptyFrames = (0 until (columnsNumber - scene.frames.count() % columnsNumber)).map { null }
I don't think, how it could look better