Add a catalogue preview images format
Alexander-Ploskin/SLIV pull request #92
Opened 2022-12-04 21:59 UTC by mi-sts

Close #40 

![catalogue-preview-format](https://user-images.githubusercontent.com/66365072/206912172-0694c989-47b7-46b4-8cda-4e1bea5ce89a.gif)

2022-12-05 08:06 UTC, DmiitriyJarosh approved these changes

2022-12-05 11:57 UTC, Alexander-Ploskin requested changes

2022-12-05 11:57 UTC, Alexander-Ploskin commented on src/main/kotlin/sliv/tool/catalogue/view/CatalogueView.kt
> +    private var displayingSelectionListener: ListChangeListener<Int>? = null
not used

2022-12-05 11:57 UTC, Alexander-Ploskin commented on src/main/kotlin/sliv/tool/catalogue/view/fields/CatalogueFieldsView.kt
>      private var isDragging = false
> ` val dragboard = root.startDragAndDrop(TransferMode.MOVE)`
When images is dragged, scrollbar also is in the dragboard.
![image](https://user-images.githubusercontent.com/55746901/205625201-caf6c660-8984-490c-b977-91c4cba9f335.png)

2022-12-05 11:57 UTC, Alexander-Ploskin commented on src/main/kotlin/sliv/tool/catalogue/view/fields/CataloguePreviewImagesFieldsView.kt
> +        labeled.graphic = vbox {
Image list view items content shakes when selected 
![Screencast from 05 12 2022 14 22 31](https://user-images.githubusercontent.com/55746901/205626034-3d362447-781f-4e55-80b2-b717bd083df5.gif)

2022-12-05 11:57 UTC, Alexander-Ploskin commented on src/main/kotlin/sliv/tool/catalogue/CatalogueUtils.kt
> +    return Image(fileInputStream)
It also used in Scene class. May be move it into some common utils file and use it everywhere

2022-12-05 11:57 UTC, Alexander-Ploskin commented on src/main/kotlin/sliv/tool/catalogue/view/fields/CatalogueFieldsView.kt
> +    val fieldsListView: ListView<CatalogueField> = listview(fields) {
Scrolling looks strange
![Screencast from 05 12 2022 14 41 45](https://user-images.githubusercontent.com/55746901/205629330-03195eaa-d3f7-4193-be2c-6fe62adab1ec.gif)

2022-12-11 15:19 UTC, mi-sts commented on src/main/kotlin/sliv/tool/catalogue/view/fields/CatalogueFieldsView.kt
> +    val fieldsListView: ListView<CatalogueField> = listview(fields) {
There are no built in support for a smooth scroll so it can be done later

2022-12-11 16:11 UTC, DmiitriyJarosh requested changes

2022-12-11 16:11 UTC, DmiitriyJarosh commented on src/main/kotlin/solve/catalogue/CatalogueUtils.kt
> +fun loadImage(path: String): Image? {
is this used only in catalog?

2022-12-11 16:11 UTC, DmiitriyJarosh commented on src/main/kotlin/solve/catalogue/CatalogueUtils.kt
> +    if (node == null) {
use let

2022-12-11 16:11 UTC, DmiitriyJarosh commented on src/main/kotlin/solve/catalogue/CatalogueUtils.kt
> +    if (node == null) {
and here

2022-12-11 16:11 UTC, DmiitriyJarosh commented on src/main/kotlin/solve/catalogue/model/CatalogueModel.kt
> +    fun differentFormat() = when (this) {
don't use such funcs, if you need boolean use it, or use selection of neded type

2022-12-11 16:11 UTC, DmiitriyJarosh commented on src/main/kotlin/solve/catalogue/view/fields/CataloguePreviewImagesFieldsView.kt
> +            return
`{}`

2022-12-11 19:05 UTC, DmiitriyJarosh approved these changes

2022-12-14 15:54 UTC, Alexander-Ploskin approved these changes

2022-12-14 16:21 UTC, merged